version: '3'
services:
   node-app:
    container_name : medososs_node
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "4001:4001"
    environment:
    - DOCKER_DEFAULT_PLATFORM=linux/amd64
    - PORT=4001

